spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        show-sql: true
        hibernate:
            format_sql: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE



#spring:
#
#    h2:
#        console:
#            enabled: true
#
#    datasource:
#        url: jdbc:h2:mem:testdb
#        driver-class-name: org.h2.Driver
#        username: sa
#        password:
#
#    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
#        hibernate:
#            ddl-auto: create-drop
#        properties:
#            hibernate:
#                format_sql: true
#                show_sql: true
#
#logging:
#    level:
#        com.tutorial: debug
